// Generated by Supabase MCP on 2026-04-22 against project uosmhbirchjudpwtptov (hyrank).
// To regenerate: run `mcp__4a3f6a92-*__generate_typescript_types` and overwrite this file.
// This is the ground-truth typed DB schema. The hand-written `lib/supabase/types.ts`
// will be migrated to re-export from here in a follow-up task.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      bumps: {
        Row: {
          bumped_at: string | null
          expires_at: string
          id: string
          ip_hash: string
          is_premium: boolean | null
          server_id: string | null
          user_id: string | null
        }
        Insert: {
          bumped_at?: string | null
          expires_at: string
          id?: string
          ip_hash: string
          is_premium?: boolean | null
          server_id?: string | null
          user_id?: string | null
        }
        Update: {
          bumped_at?: string | null
          expires_at?: string
          id?: string
          ip_hash?: string
          is_premium?: boolean | null
          server_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bumps_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "bumps_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      featured_auctions: {
        Row: {
          bid_amount: number
          bidder_id: string | null
          created_at: string | null
          end_date: string
          id: string
          position: number
          server_id: string | null
          start_date: string
          status: string
        }
        Insert: {
          bid_amount: number
          bidder_id?: string | null
          created_at?: string | null
          end_date: string
          id?: string
          position: number
          server_id?: string | null
          start_date: string
          status?: string
        }
        Update: {
          bid_amount?: number
          bidder_id?: string | null
          created_at?: string | null
          end_date?: string
          id?: string
          position?: number
          server_id?: string | null
          start_date?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "featured_auctions_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "featured_auctions_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      gamemodes: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          slug: string
          sort_order: number | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          slug: string
          sort_order?: number | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          slug?: string
          sort_order?: number | null
        }
        Relationships: []
      }
      moderation_log: {
        Row: {
          created_at: string | null
          event_type: string
          id: string
          metadata: Json | null
          quantity: number | null
          reason: string | null
          subject_id: string | null
          subject_id_hash: string | null
          subject_type: string
        }
        Insert: {
          created_at?: string | null
          event_type: string
          id?: string
          metadata?: Json | null
          quantity?: number | null
          reason?: string | null
          subject_id?: string | null
          subject_id_hash?: string | null
          subject_type: string
        }
        Update: {
          created_at?: string | null
          event_type?: string
          id?: string
          metadata?: Json | null
          quantity?: number | null
          reason?: string | null
          subject_id?: string | null
          subject_id_hash?: string | null
          subject_type?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          discord_id: string | null
          discord_username: string | null
          email_verified: boolean | null
          flag_reason: string | null
          flagged: boolean | null
          hytale_username: string | null
          hytale_uuid: string | null
          hytale_verified_at: string | null
          id: string
          ip_addresses: string[] | null
          longest_streak: number | null
          total_votes: number | null
          trust_tier: string
          updated_at: string | null
          username: string | null
          vote_streak: number | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          discord_id?: string | null
          discord_username?: string | null
          email_verified?: boolean | null
          flag_reason?: string | null
          flagged?: boolean | null
          hytale_username?: string | null
          hytale_uuid?: string | null
          hytale_verified_at?: string | null
          id: string
          ip_addresses?: string[] | null
          longest_streak?: number | null
          total_votes?: number | null
          trust_tier?: string
          updated_at?: string | null
          username?: string | null
          vote_streak?: number | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          discord_id?: string | null
          discord_username?: string | null
          email_verified?: boolean | null
          flag_reason?: string | null
          flagged?: boolean | null
          hytale_username?: string | null
          hytale_uuid?: string | null
          hytale_verified_at?: string | null
          id?: string
          ip_addresses?: string[] | null
          longest_streak?: number | null
          total_votes?: number | null
          trust_tier?: string
          updated_at?: string | null
          username?: string | null
          vote_streak?: number | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          content: string | null
          created_at: string | null
          helpful_count: number | null
          id: string
          owner_response: string | null
          owner_response_at: string | null
          rating: number | null
          reported: boolean | null
          server_id: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          helpful_count?: number | null
          id?: string
          owner_response?: string | null
          owner_response_at?: string | null
          rating?: number | null
          reported?: boolean | null
          server_id?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          helpful_count?: number | null
          id?: string
          owner_response?: string | null
          owner_response_at?: string | null
          rating?: number | null
          reported?: boolean | null
          server_id?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "reviews_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_servers: {
        Row: {
          id: string
          saved_at: string | null
          server_id: string | null
          user_id: string | null
        }
        Insert: {
          id?: string
          saved_at?: string | null
          server_id?: string | null
          user_id?: string | null
        }
        Update: {
          id?: string
          saved_at?: string | null
          server_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "saved_servers_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "saved_servers_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_gamemodes: {
        Row: {
          created_at: string | null
          gamemode_id: string
          is_primary: boolean | null
          server_id: string
        }
        Insert: {
          created_at?: string | null
          gamemode_id: string
          is_primary?: boolean | null
          server_id: string
        }
        Update: {
          created_at?: string | null
          gamemode_id?: string
          is_primary?: boolean | null
          server_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "server_gamemodes_gamemode_id_fkey"
            columns: ["gamemode_id"]
            isOneToOne: false
            referencedRelation: "gamemodes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "server_gamemodes_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_gamemodes_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_mods: {
        Row: {
          created_at: string | null
          curseforge_mod_id: number
          declared_by: string
          server_id: string
          version: string | null
        }
        Insert: {
          created_at?: string | null
          curseforge_mod_id: number
          declared_by?: string
          server_id: string
          version?: string | null
        }
        Update: {
          created_at?: string | null
          curseforge_mod_id?: number
          declared_by?: string
          server_id?: string
          version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "server_mods_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_mods_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_owners: {
        Row: {
          created_at: string | null
          evidence: Json | null
          id: string
          method: string
          server_id: string
          status: string
          token: string
          user_id: string
          verified_at: string | null
        }
        Insert: {
          created_at?: string | null
          evidence?: Json | null
          id?: string
          method: string
          server_id: string
          status?: string
          token: string
          user_id: string
          verified_at?: string | null
        }
        Update: {
          created_at?: string | null
          evidence?: Json | null
          id?: string
          method?: string
          server_id?: string
          status?: string
          token?: string
          user_id?: string
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "server_owners_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_owners_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_rank: {
        Row: {
          bayesian_quality: number | null
          composite_score: number
          computed_at: string | null
          hot_velocity: number | null
          live_signal: number | null
          retention: number | null
          server_id: string
          shadow_fraud_penalty: number | null
          uptime_signal: number | null
        }
        Insert: {
          bayesian_quality?: number | null
          composite_score?: number
          computed_at?: string | null
          hot_velocity?: number | null
          live_signal?: number | null
          retention?: number | null
          server_id: string
          shadow_fraud_penalty?: number | null
          uptime_signal?: number | null
        }
        Update: {
          bayesian_quality?: number | null
          composite_score?: number
          computed_at?: string | null
          hot_velocity?: number | null
          live_signal?: number | null
          retention?: number | null
          server_id?: string
          shadow_fraud_penalty?: number | null
          uptime_signal?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "server_rank_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: true
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_rank_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: true
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_status_history: {
        Row: {
          id: string
          latency: number | null
          players_online: number | null
          recorded_at: string | null
          server_id: string | null
          status: string | null
        }
        Insert: {
          id?: string
          latency?: number | null
          players_online?: number | null
          recorded_at?: string | null
          server_id?: string | null
          status?: string | null
        }
        Update: {
          id?: string
          latency?: number | null
          players_online?: number | null
          recorded_at?: string | null
          server_id?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "server_status_history_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_status_history_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
      server_tags: {
        Row: {
          is_primary: boolean | null
          server_id: string
          tag_id: string
        }
        Insert: {
          is_primary?: boolean | null
          server_id: string
          tag_id: string
        }
        Update: {
          is_primary?: boolean | null
          server_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "server_tags_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "server_tags_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "server_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      servers: {
        Row: {
          banner: string | null
          banners: string[] | null
          bump_count: number | null
          click_count: number | null
          country: string | null
          created_at: string | null
          description: string | null
          discord: string | null
          featured: boolean | null
          featured_order: number | null
          icon: string | null
          id: string
          ip: string
          is_premium: boolean | null
          last_bump: string | null
          last_ping: string | null
          last_seen_online: string | null
          latency: number | null
          monthly_votes: number | null
          motd: string | null
          name: string
          offline_since: string | null
          owner_id: string | null
          players_max: number | null
          players_online: number | null
          port: number | null
          query_port: number | null
          ranking_score: number | null
          rating_avg: number | null
          rating_count: number | null
          region: string | null
          slug: string | null
          status: string | null
          tags: string[] | null
          trust_tier: string
          twitter: string | null
          updated_at: string | null
          uptime_day: number | null
          uptime_month: number | null
          uptime_week: number | null
          verified: boolean | null
          version: string | null
          view_count: number | null
          vote_count: number | null
          votifier_enabled: boolean | null
          votifier_ip: string | null
          votifier_last_test: string | null
          votifier_last_test_success: boolean | null
          votifier_port: number | null
          votifier_public_key: string | null
          votifier_secret_key: string | null
          website: string | null
          weekly_votes: number | null
          youtube: string | null
        }
        Insert: {
          banner?: string | null
          banners?: string[] | null
          bump_count?: number | null
          click_count?: number | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          discord?: string | null
          featured?: boolean | null
          featured_order?: number | null
          icon?: string | null
          id?: string
          ip: string
          is_premium?: boolean | null
          last_bump?: string | null
          last_ping?: string | null
          last_seen_online?: string | null
          latency?: number | null
          monthly_votes?: number | null
          motd?: string | null
          name: string
          offline_since?: string | null
          owner_id?: string | null
          players_max?: number | null
          players_online?: number | null
          port?: number | null
          query_port?: number | null
          ranking_score?: number | null
          rating_avg?: number | null
          rating_count?: number | null
          region?: string | null
          slug?: string | null
          status?: string | null
          tags?: string[] | null
          trust_tier?: string
          twitter?: string | null
          updated_at?: string | null
          uptime_day?: number | null
          uptime_month?: number | null
          uptime_week?: number | null
          verified?: boolean | null
          version?: string | null
          view_count?: number | null
          vote_count?: number | null
          votifier_enabled?: boolean | null
          votifier_ip?: string | null
          votifier_last_test?: string | null
          votifier_last_test_success?: boolean | null
          votifier_port?: number | null
          votifier_public_key?: string | null
          votifier_secret_key?: string | null
          website?: string | null
          weekly_votes?: number | null
          youtube?: string | null
        }
        Update: {
          banner?: string | null
          banners?: string[] | null
          bump_count?: number | null
          click_count?: number | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          discord?: string | null
          featured?: boolean | null
          featured_order?: number | null
          icon?: string | null
          id?: string
          ip?: string
          is_premium?: boolean | null
          last_bump?: string | null
          last_ping?: string | null
          last_seen_online?: string | null
          latency?: number | null
          monthly_votes?: number | null
          motd?: string | null
          name?: string
          offline_since?: string | null
          owner_id?: string | null
          players_max?: number | null
          players_online?: number | null
          port?: number | null
          query_port?: number | null
          ranking_score?: number | null
          rating_avg?: number | null
          rating_count?: number | null
          region?: string | null
          slug?: string | null
          status?: string | null
          tags?: string[] | null
          trust_tier?: string
          twitter?: string | null
          updated_at?: string | null
          uptime_day?: number | null
          uptime_month?: number | null
          uptime_week?: number | null
          verified?: boolean | null
          version?: string | null
          view_count?: number | null
          vote_count?: number | null
          votifier_enabled?: boolean | null
          votifier_ip?: string | null
          votifier_last_test?: string | null
          votifier_last_test_success?: boolean | null
          votifier_port?: number | null
          votifier_public_key?: string | null
          votifier_secret_key?: string | null
          website?: string | null
          weekly_votes?: number | null
          youtube?: string | null
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          created_at: string | null
          current_period_end: string | null
          current_period_start: string | null
          id: string
          status: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          tier: string
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          tier?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          tier?: string
          user_id?: string | null
        }
        Relationships: []
      }
      tags: {
        Row: {
          approved: boolean | null
          created_at: string | null
          created_by: string | null
          id: string
          name: string
          slug: string
        }
        Insert: {
          approved?: boolean | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          name: string
          slug: string
        }
        Update: {
          approved?: boolean | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
      vote_deliveries: {
        Row: {
          attempts: number | null
          created_at: string | null
          error_message: string | null
          id: string
          last_attempt: string | null
          next_retry: string | null
          server_id: string | null
          status: string
          username: string
          vote_id: string | null
        }
        Insert: {
          attempts?: number | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          last_attempt?: string | null
          next_retry?: string | null
          server_id?: string | null
          status?: string
          username: string
          vote_id?: string | null
        }
        Update: {
          attempts?: number | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          last_attempt?: string | null
          next_retry?: string | null
          server_id?: string | null
          status?: string
          username?: string
          vote_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "vote_deliveries_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "vote_deliveries_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vote_deliveries_vote_id_fkey"
            columns: ["vote_id"]
            isOneToOne: false
            referencedRelation: "votes"
            referencedColumns: ["id"]
          },
        ]
      }
      votes: {
        Row: {
          claimed_at: string | null
          created_at: string | null
          id: string
          ip_hash: string
          server_id: string | null
          source: string | null
          status: string
          trust_score: number | null
          ua_hash: string | null
          user_agent: string | null
          user_id: string | null
          visitor_id: string | null
          vote_bucket: number | null
        }
        Insert: {
          claimed_at?: string | null
          created_at?: string | null
          id?: string
          ip_hash: string
          server_id?: string | null
          source?: string | null
          status?: string
          trust_score?: number | null
          ua_hash?: string | null
          user_agent?: string | null
          user_id?: string | null
          visitor_id?: string | null
          vote_bucket?: number | null
        }
        Update: {
          claimed_at?: string | null
          created_at?: string | null
          id?: string
          ip_hash?: string
          server_id?: string | null
          source?: string | null
          status?: string
          trust_score?: number | null
          ua_hash?: string | null
          user_agent?: string | null
          user_id?: string | null
          visitor_id?: string | null
          vote_bucket?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "votes_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "server_signals"
            referencedColumns: ["server_id"]
          },
          {
            foreignKeyName: "votes_server_id_fkey"
            columns: ["server_id"]
            isOneToOne: false
            referencedRelation: "servers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      server_signals: {
        Row: {
          first_vote_7d: string | null
          live_players: number | null
          rating_avg: number | null
          rating_count: number | null
          refreshed_at: string | null
          server_id: string | null
          shadow_votes_7d: number | null
          uptime_30d: number | null
          valid_votes_7d: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      calculate_uptime: {
        Args: { hours: number; server_uuid: string }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
