/**
 * Source-of-truth types come from ./database.types.ts (generated by Supabase MCP).
 * This file re-exports the Database type and common row helpers so existing
 * callers that imported from "@/lib/supabase/types" continue to work unchanged.
 * When regenerating types, run `mcp__4a3f6a92-*__generate_typescript_types`
 * and overwrite database.types.ts — this file does not need edits.
 */
export type { Database, Json, Tables, TablesInsert, TablesUpdate, Enums, CompositeTypes } from "./database.types";
import type { Database } from "./database.types";

// Legacy convenience aliases used by older call sites.
export type ServerRow = Database["public"]["Tables"]["servers"]["Row"];
export type VoteRow = Database["public"]["Tables"]["votes"]["Row"];
export type ReviewRow = Database["public"]["Tables"]["reviews"]["Row"];
export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];
export type SavedServerRow = Database["public"]["Tables"]["saved_servers"]["Row"];
export type GamemodeRow = Database["public"]["Tables"]["gamemodes"]["Row"];
export type TagRow = Database["public"]["Tables"]["tags"]["Row"];
export type ServerOwnerRow = Database["public"]["Tables"]["server_owners"]["Row"];
export type ServerRankRow = Database["public"]["Tables"]["server_rank"]["Row"];
export type ServerSignalsView = Database["public"]["Views"]["server_signals"]["Row"];
